# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LocationEvent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13LocationEvent.proto\"M\n\x14LocationEventMessage\x12\x10\n\x08personId\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2k\n\x0bItemService\x12\x36\n\x06\x43reate\x12\x15.LocationEventMessage\x1a\x15.LocationEventMessage\x12$\n\x03Get\x12\x06.Empty\x1a\x15.LocationEventMessageb\x06proto3')

_LOCATIONEVENTMESSAGE = DESCRIPTOR.message_types_by_name['LocationEventMessage']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
LocationEventMessage = _reflection.GeneratedProtocolMessageType('LocationEventMessage', (_message.Message,), {
    'DESCRIPTOR': _LOCATIONEVENTMESSAGE,
    '__module__': 'LocationEvent_pb2'
    # @@protoc_insertion_point(class_scope:LocationEventMessage)
})
_sym_db.RegisterMessage(LocationEventMessage)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
    'DESCRIPTOR': _EMPTY,
    '__module__': 'LocationEvent_pb2'
    # @@protoc_insertion_point(class_scope:Empty)
})
_sym_db.RegisterMessage(Empty)

_ITEMSERVICE = DESCRIPTOR.services_by_name['ItemService']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _LOCATIONEVENTMESSAGE._serialized_start = 23
    _LOCATIONEVENTMESSAGE._serialized_end = 100
    _EMPTY._serialized_start = 102
    _EMPTY._serialized_end = 109
    _ITEMSERVICE._serialized_start = 111
    _ITEMSERVICE._serialized_end = 218
# @@protoc_insertion_point(module_scope)
