apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-locations-consumer
  name: locations-consumer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30010
  selector:
    service: api-locations-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: api-locations-consumer
  name: api-locations-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api-locations-consumer
  template:
    metadata:
      labels:
        service: api-locations-consumer
    spec:
      containers:
      - image: nguyenson99/api-locations-consumer:latest
        name: api-locations-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_TOPIC
        
      restartPolicy: Always
